apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appvenda-dash-pvc-graph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi