apiVersion: v1
kind: PersistentVolume
metadata:
  name: appvenda-dash-pv-graph
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\Users\bruno\devops_infnet\k8s\pv_dash
