<<<<<<< HEAD
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'appvenda'
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'appvenda'
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
>>>>>>> origin/main
          - targets: ['10.98.184.91:8081']