apiVersion: v1
kind: PersistentVolume
metadata:
  name: appvenda-prometheus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: C:\Users\bruno\devops_infnet\k8s\pv_prometheus
