<<<<<<< HEAD
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appvenda-prometheus-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
=======
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appvenda-prometheus-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
>>>>>>> origin/main
    - ReadWriteMany