apiVersion: v1
kind: Service
metadata:
  name: appvenda-prometheus-service
spec:
  selector:
    app: appvenda-prometheus
  ports:
    - name: port-9090
      protocol: TCP
      port: 9090
      targetPort: 9090