global:
  scrape_interval: 15s # Define a frequência em que o Prometheus irá coletar métricas dos alvos.
  scrape_timeout: 10s # Define o tempo limite para a coleta de métricas de um alvo.

scrape_configs:
  - job_name: 'prometheus' # Nome da configuração de coleta
    static_configs:
      - targets: ['localhost:9090'] # Endereço onde o node_exporter está escutando
  - job_name: 'appvenda'
    metrics_path: "/actuator/prometheus" # Caminho onde a aplicação expõe as métricas
    scrape_interval: 3s # Define a frequência em que o Prometheus irá coletar métricas dos alvos.
    static_configs:      
      - targets: ['10.98.184.91:8081'] # Endereço onde a sua aplicação está escutando