<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-site
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30010
=======
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-site
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30010
>>>>>>> origin/main
  type: NodePort