apiVersion: v1
kind: Pod
metadata:
  name: appvenda-jmeter-pod
  labels:
    app: appvenda-jmeter
spec:
  containers:
  - name: jmeter-container
    image: justb4/jmeter:latest
    command: ["/bin/sh", "-c", "jmeter -n -t /tmp/test-plan/test_plan.jmx -l /tmp/test-results/test_results.jtl -e -o /tmp/test-results/dashboard"]
    volumeMounts:
    - name: test-plan
      mountPath: /tmp/test-plan
      readOnly: true
    - name: test-results
      mountPath: /tmp/test-results
      readOnly: false
  volumes:
  - name: test-plan
    hostPath:
      path: C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\testes
      type: Directory
  - name: test-results
    hostPath:
      path: C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\resultados
      type: Directory

#docker run -d --name jmeter-teste -v C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\testes:/tmp/test-plan -v C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\resultados:/tmp/test-results --entrypoint "/bin/sh" justb4/jmeter -c "jmeter -n -t /tmp/test-plan/test_plan.jmx -l /tmp/test-results/test_results.jtl -e -o /tmp/test-results/dashboard"