apiVersion: v1
kind: Pod
metadata:
  name: appvenda-jmeter-pod
  labels:
    app: appvenda-jmeter
spec:
  containers:
  - name: jmeter-container
    image: justb4/jmeter:latest
    command: ["jmeter", "-n", "-t", "/test-plan/test_plan.jmx", "-l", "/test-results/test_results.jtl"]
    volumeMounts:
    - name: test-plan
      mountPath: /test-plan
    - name: test-results
      mountPath: /test-results
  volumes:
  - name: test-plan
    hostPath:
      path: C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\testes\
  - name: test-results
    hostPath:
      path: C:\Users\bruno\devops_infnet\k8s\k8s_appvenda_jmeter\resultados\


